Type = "jscript"
Intro = "hell全能脚本"
Desc = ""
OnOpen = "onOpen"
OnClose = "onClose"
OnConnect = "onConnected"
OnDisconnect = "onDisconnected"
OnBroadcast = "onBroadcast"
OnFocus = ""
OnKeyUp = "OnKeyUp"
OnHUDClick = ""
OnResponse = "onResponse"
OnAssist = "onAssist"
OnBuffer = "onBuffer"
OnSubneg = ""
OnBufferMin = 0
OnBufferMax = 0
Channel = ""

[[Triggers]]
  ID = "d1f98164pfr1go7151pg53"
  Name = "App.Online"
  Enabled = true
  Match = "^"
  Send = ""
  ColourChangeType = 0
  Colour = 0
  Wildcard = 0
  SoundFileName = ""
  SoundIfInactive = false
  Script = "App.Online"
  SendTo = 0
  Sequence = 50
  ExpandVariables = false
  Temporary = false
  OneShot = false
  Regexp = true
  Repeat = false
  MultiLine = false
  LinesToMatch = 0
  WildcardLowerCase = false
  Group = ""
  IgnoreCase = false
  KeepEvaluating = true
  OmitFromLog = false
  OmitFromOutput = false
  Inverse = false
  Italic = false
  Variable = ""

[[Triggers]]
  ID = "d1f980vq1qbpo17151pfv6"
  Name = "App.Core.Room.OnExits"
  Enabled = true
  Match = "^    这里(唯一的出口是|明显的出口是|没有任何明显的出路)(.*)"
  Send = ""
  ColourChangeType = 0
  Colour = 0
  Wildcard = 0
  SoundFileName = ""
  SoundIfInactive = false
  Script = "App.Core.Room.OnExits"
  SendTo = 0
  Sequence = 100
  ExpandVariables = false
  Temporary = false
  OneShot = false
  Regexp = true
  Repeat = false
  MultiLine = false
  LinesToMatch = 0
  WildcardLowerCase = false
  Group = ""
  IgnoreCase = false
  KeepEvaluating = true
  OmitFromLog = false
  OmitFromOutput = false
  Inverse = false
  Italic = false
  Variable = ""

[[Triggers]]
  ID = "d1f985tqb73ivs7151pk8d"
  Name = "App.Core.Room.OnObj"
  Enabled = true
  Match = "^    ([^()]+)\\(([a-zA-Z ]+)\\)(\\s*<.+>)*(\\s*\\[.+\\])*$"
  Send = ""
  ColourChangeType = 0
  Colour = 0
  Wildcard = 0
  SoundFileName = ""
  SoundIfInactive = false
  Script = "App.Core.Room.OnObj"
  SendTo = 0
  Sequence = 100
  ExpandVariables = false
  Temporary = false
  OneShot = false
  Regexp = true
  Repeat = false
  MultiLine = false
  LinesToMatch = 0
  WildcardLowerCase = false
  Group = ""
  IgnoreCase = false
  KeepEvaluating = true
  OmitFromLog = false
  OmitFromOutput = false
  Inverse = false
  Italic = false
  Variable = ""

[[Triggers]]
  ID = "d1f9ohdik3tn4f714ehvkf"
  Name = "App.Core.OnResponse"
  Enabled = true
  Match = "^设定环境变数：no_more = \"([^-]+)\\-([^=]+)(=(.*)){0,1}\"$"
  Send = ""
  ColourChangeType = 0
  Colour = 0
  Wildcard = 0
  SoundFileName = ""
  SoundIfInactive = false
  Script = "App.Core.OnResponse"
  SendTo = 0
  Sequence = 100
  ExpandVariables = false
  Temporary = false
  OneShot = false
  Regexp = true
  Repeat = false
  MultiLine = false
  LinesToMatch = 0
  WildcardLowerCase = false
  Group = ""
  IgnoreCase = false
  KeepEvaluating = true
  OmitFromLog = false
  OmitFromOutput = false
  Inverse = false
  Italic = false
  Variable = ""

[[Triggers]]
  ID = "d1f9r9itglcptf714ejfeo"
  Name = "App.Core.Player.OnHpStart"
  Enabled = true
  Match = "^┌───个人状态────────────┬───────────────────┐$"
  Send = ""
  ColourChangeType = 0
  Colour = 0
  Wildcard = 0
  SoundFileName = ""
  SoundIfInactive = false
  Script = "App.Core.Player.OnHpStart"
  SendTo = 0
  Sequence = 100
  ExpandVariables = false
  Temporary = false
  OneShot = false
  Regexp = true
  Repeat = false
  MultiLine = false
  LinesToMatch = 0
  WildcardLowerCase = false
  Group = ""
  IgnoreCase = false
  KeepEvaluating = true
  OmitFromLog = false
  OmitFromOutput = false
  Inverse = false
  Italic = false
  Variable = ""

[[Triggers]]
  ID = "d1f9ras9uifvua714ejhks"
  Name = "App.Core.Player.OnHpLine1"
  Enabled = true
  Match = "^│\\s*【精气】\\s*(-{0,1}\\d*)\\s*/\\s*(-{0,1}\\d*)\\s*\\[\\s*(\\d*)%\\](.*)【精力】\\s*(-{0,1}\\d*)\\s*/\\s*(-{0,1}\\d*)\\s*\\((.*)\\)\\s*│$"
  Send = ""
  ColourChangeType = 0
  Colour = 0
  Wildcard = 0
  SoundFileName = ""
  SoundIfInactive = false
  Script = "App.Core.Player.OnHpLine1"
  SendTo = 0
  Sequence = 100
  ExpandVariables = false
  Temporary = false
  OneShot = false
  Regexp = true
  Repeat = false
  MultiLine = false
  LinesToMatch = 0
  WildcardLowerCase = false
  Group = ""
  IgnoreCase = false
  KeepEvaluating = true
  OmitFromLog = false
  OmitFromOutput = false
  Inverse = false
  Italic = false
  Variable = ""

[[Triggers]]
  ID = "d1f9rb4aharjlu714eji0m"
  Name = "App.Core.Player.OnHpLine2"
  Enabled = true
  Match = "^│\\s*【气血】\\s*(-{0,1}\\d*)\\s*/\\s*(-{0,1}\\d*)\\s*\\[\\s*(\\d*)%\\](.*)【内力】\\s*(-{0,1}\\d*)\\s*/\\s*(-{0,1}\\d*)\\s*\\(\\+\\s*(\\S+)\\)\\s*│$"
  Send = ""
  ColourChangeType = 0
  Colour = 0
  Wildcard = 0
  SoundFileName = ""
  SoundIfInactive = false
  Script = "App.Core.Player.OnHpLine2"
  SendTo = 0
  Sequence = 100
  ExpandVariables = false
  Temporary = false
  OneShot = false
  Regexp = true
  Repeat = false
  MultiLine = false
  LinesToMatch = 0
  WildcardLowerCase = false
  Group = ""
  IgnoreCase = false
  KeepEvaluating = true
  OmitFromLog = false
  OmitFromOutput = false
  Inverse = false
  Italic = false
  Variable = ""

[[Triggers]]
  ID = "d1f9rbkvtoukb1714ejite"
  Name = "App.Core.Player.OnHpLine3"
  Enabled = true
  Match = "^│【食物】([^/]*)/\\s*(\\S*).+【潜能】(.*)│$"
  Send = ""
  ColourChangeType = 0
  Colour = 0
  Wildcard = 0
  SoundFileName = ""
  SoundIfInactive = false
  Script = "App.Core.Player.OnHpLine3"
  SendTo = 0
  Sequence = 100
  ExpandVariables = false
  Temporary = false
  OneShot = false
  Regexp = true
  Repeat = false
  MultiLine = false
  LinesToMatch = 0
  WildcardLowerCase = false
  Group = ""
  IgnoreCase = false
  KeepEvaluating = true
  OmitFromLog = false
  OmitFromOutput = false
  Inverse = false
  Italic = false
  Variable = ""

[[Triggers]]
  ID = "d1f9rbukajrch6714ejjej"
  Name = "App.Core.Player.OnHpLine4"
  Enabled = true
  Match = "^│【饮水】([^/]*)/\\s*(\\S*).+【经验】(.*)│$"
  Send = ""
  ColourChangeType = 0
  Colour = 0
  Wildcard = 0
  SoundFileName = ""
  SoundIfInactive = false
  Script = "App.Core.Player.OnHpLine4"
  SendTo = 0
  Sequence = 100
  ExpandVariables = false
  Temporary = false
  OneShot = false
  Regexp = true
  Repeat = false
  MultiLine = false
  LinesToMatch = 0
  WildcardLowerCase = false
  Group = ""
  IgnoreCase = false
  KeepEvaluating = true
  OmitFromLog = false
  OmitFromOutput = false
  Inverse = false
  Italic = false
  Variable = ""

[[Triggers]]
  ID = "d1f9rcdg05ko8r714ejk3a"
  Name = "App.Core.Player.OnHpLine5"
  Enabled = true
  Match = "^│\\s+│【体会】 (\\S+)\\s*│$"
  Send = ""
  ColourChangeType = 0
  Colour = 0
  Wildcard = 0
  SoundFileName = ""
  SoundIfInactive = false
  Script = "App.Core.Player.OnHpLine5"
  SendTo = 0
  Sequence = 100
  ExpandVariables = false
  Temporary = false
  OneShot = false
  Regexp = true
  Repeat = false
  MultiLine = false
  LinesToMatch = 0
  WildcardLowerCase = false
  Group = ""
  IgnoreCase = false
  KeepEvaluating = true
  OmitFromLog = false
  OmitFromOutput = false
  Inverse = false
  Italic = false
  Variable = ""

[[Triggers]]
  ID = "d1f9rddcja3ds8714ejlm3"
  Name = "App.Core.Player.OnSkillsStart"
  Enabled = true
  Match = "^(你目前并没有学会任何技能。|你目前所学到的所有技能)$"
  Send = ""
  ColourChangeType = 0
  Colour = 0
  Wildcard = 0
  SoundFileName = ""
  SoundIfInactive = false
  Script = "App.Core.Player.OnSkillsStart"
  SendTo = 0
  Sequence = 100
  ExpandVariables = false
  Temporary = false
  OneShot = false
  Regexp = true
  Repeat = false
  MultiLine = false
  LinesToMatch = 0
  WildcardLowerCase = false
  Group = ""
  IgnoreCase = false
  KeepEvaluating = true
  OmitFromLog = false
  OmitFromOutput = false
  Inverse = false
  Italic = false
  Variable = ""

[[Triggers]]
  ID = "d1f9rdr8srvqdf714ejm9d"
  Name = "App.Core.Player.OnSkillType"
  Enabled = true
  Match = "^├\\S+项(基本功夫|知识技能|其它技能)─*┼─*┼─*┼─*┤$"
  Send = ""
  ColourChangeType = 0
  Colour = 0
  Wildcard = 0
  SoundFileName = ""
  SoundIfInactive = false
  Script = "App.Core.Player.OnSkillType"
  SendTo = 0
  Sequence = 100
  ExpandVariables = false
  Temporary = false
  OneShot = false
  Regexp = true
  Repeat = false
  MultiLine = false
  LinesToMatch = 0
  WildcardLowerCase = false
  Group = ""
  IgnoreCase = false
  KeepEvaluating = true
  OmitFromLog = false
  OmitFromOutput = false
  Inverse = false
  Italic = false
  Variable = ""

[[Triggers]]
  ID = "d1f9re2acuupon714ejmib"
  Name = "App.Core.Player.OnSkill"
  Enabled = true
  Match = "^│(□|  )(\\S+)\\s*│(\\S+)\\s*│[^│]+│\\s*([^ /]+)\\s*/\\s*(\\S+)\\s*│$"
  Send = ""
  ColourChangeType = 0
  Colour = 0
  Wildcard = 0
  SoundFileName = ""
  SoundIfInactive = false
  Script = "App.Core.Player.OnSkill"
  SendTo = 0
  Sequence = 100
  ExpandVariables = false
  Temporary = false
  OneShot = false
  Regexp = true
  Repeat = false
  MultiLine = false
  LinesToMatch = 0
  WildcardLowerCase = false
  Group = ""
  IgnoreCase = false
  KeepEvaluating = true
  OmitFromLog = false
  OmitFromOutput = false
  Inverse = false
  Italic = false
  Variable = ""

[[Triggers]]
  ID = "d1f9s6v6fq47pf73e3lsqs"
  Name = "App.Core.Inv.OnItemsStart"
  Enabled = true
  Match = "^你身上带著下列这些东西\\(负重\\s*(\\S+)%\\)：$"
  Send = ""
  ColourChangeType = 0
  Colour = 0
  Wildcard = 0
  SoundFileName = ""
  SoundIfInactive = false
  Script = "App.Core.Inv.OnItemsStart"
  SendTo = 0
  Sequence = 100
  ExpandVariables = false
  Temporary = false
  OneShot = false
  Regexp = true
  Repeat = false
  MultiLine = false
  LinesToMatch = 0
  WildcardLowerCase = false
  Group = ""
  IgnoreCase = false
  KeepEvaluating = true
  OmitFromLog = false
  OmitFromOutput = false
  Inverse = false
  Italic = false
  Variable = ""

[[Triggers]]
  ID = "d1f9s75s6dtua073e3lstm"
  Name = "App.Core.Inv.OnItemsEnd"
  Enabled = true
  Match = "^目前携带了(.+)件物品。$"
  Send = ""
  ColourChangeType = 0
  Colour = 0
  Wildcard = 0
  SoundFileName = ""
  SoundIfInactive = false
  Script = "App.Core.Inv.OnItemsEnd"
  SendTo = 0
  Sequence = 100
  ExpandVariables = false
  Temporary = false
  OneShot = false
  Regexp = true
  Repeat = false
  MultiLine = false
  LinesToMatch = 0
  WildcardLowerCase = false
  Group = ""
  IgnoreCase = false
  KeepEvaluating = true
  OmitFromLog = false
  OmitFromOutput = false
  Inverse = false
  Italic = false
  Variable = ""

[[Triggers]]
  ID = "d1f9s7br3fe5m673e3lsv8"
  Name = "App.Core.Inv.OnItem"
  Enabled = true
  Match = "^(□|○|  )([^ (]+)\\(([^)]+)\\)$"
  Send = ""
  ColourChangeType = 0
  Colour = 0
  Wildcard = 0
  SoundFileName = ""
  SoundIfInactive = false
  Script = "App.Core.Inv.OnItem"
  SendTo = 0
  Sequence = 100
  ExpandVariables = false
  Temporary = false
  OneShot = false
  Regexp = true
  Repeat = false
  MultiLine = false
  LinesToMatch = 0
  WildcardLowerCase = false
  Group = ""
  IgnoreCase = false
  KeepEvaluating = true
  OmitFromLog = false
  OmitFromOutput = false
  Inverse = false
  Italic = false
  Variable = ""

[[Triggers]]
  ID = "d1f9s86t0m88lv73e3lta1"
  Name = "App.Core.Inv.OnItemsEmpty"
  Enabled = true
  Match = "^目前你身上没有任何东西。$"
  Send = ""
  ColourChangeType = 0
  Colour = 0
  Wildcard = 0
  SoundFileName = ""
  SoundIfInactive = false
  Script = "App.Core.Inv.OnItemsEmpty"
  SendTo = 0
  Sequence = 100
  ExpandVariables = false
  Temporary = false
  OneShot = false
  Regexp = true
  Repeat = false
  MultiLine = false
  LinesToMatch = 0
  WildcardLowerCase = false
  Group = ""
  IgnoreCase = false
  KeepEvaluating = true
  OmitFromLog = false
  OmitFromOutput = false
  Inverse = false
  Italic = false
  Variable = ""

[[Triggers]]
  ID = "d1fa325tbnstqq6qr8h2k"
  Name = "App.Core.OnBusyEnd"
  Enabled = true
  Match = "^指令格式：apprentice \\| bai \\[cancel\\]\\|<对象>$"
  Send = ""
  ColourChangeType = 0
  Colour = 0
  Wildcard = 0
  SoundFileName = ""
  SoundIfInactive = false
  Script = "App.Core.OnBusyEnd"
  SendTo = 0
  Sequence = 100
  ExpandVariables = false
  Temporary = false
  OneShot = false
  Regexp = true
  Repeat = false
  MultiLine = false
  LinesToMatch = 0
  WildcardLowerCase = false
  Group = ""
  IgnoreCase = false
  KeepEvaluating = true
  OmitFromLog = false
  OmitFromOutput = false
  Inverse = false
  Italic = false
  Variable = ""

[[Triggers]]
  ID = "d1fa7i570vlnqc6qr9v7s"
  Name = "App.Core.Repair.OnDurability"
  Enabled = true
  Match = "^耐 久 值 : (\\d+)/(\\d+)$"
  Send = ""
  ColourChangeType = 0
  Colour = 0
  Wildcard = 0
  SoundFileName = ""
  SoundIfInactive = false
  Script = "App.Core.Repair.OnDurability"
  SendTo = 0
  Sequence = 100
  ExpandVariables = false
  Temporary = false
  OneShot = false
  Regexp = true
  Repeat = false
  MultiLine = false
  LinesToMatch = 0
  WildcardLowerCase = false
  Group = ""
  IgnoreCase = false
  KeepEvaluating = true
  OmitFromLog = false
  OmitFromOutput = false
  Inverse = false
  Italic = false
  Variable = ""

[[Triggers]]
  ID = "d1f9rdj4m9i6pv714ejlvu"
  Name = "App.OnAfterline"
  Enabled = true
  Match = "^"
  Send = ""
  ColourChangeType = 0
  Colour = 0
  Wildcard = 0
  SoundFileName = ""
  SoundIfInactive = false
  Script = "App.OnAfterline"
  SendTo = 0
  Sequence = 999
  ExpandVariables = false
  Temporary = false
  OneShot = false
  Regexp = true
  Repeat = false
  MultiLine = false
  LinesToMatch = 0
  WildcardLowerCase = false
  Group = ""
  IgnoreCase = false
  KeepEvaluating = true
  OmitFromLog = false
  OmitFromOutput = false
  Inverse = false
  Italic = false
  Variable = ""

[[Timers]]
  ID = "d1f9p0iank200o714ej09t"
  Name = "App.Core.OnBusyRetry"
  Enabled = false
  Hour = 0
  Minute = 0
  Second = 1.0
  Send = ""
  Script = "App.Core.OnBusyRetry"
  AtTime = false
  SendTo = 0
  ActionWhenDisconnectd = false
  Temporary = false
  OneShot = false
  Group = ""
  Variable = ""
  OmitFromLog = false
  OmitFromOutput = false

[[Aliases]]
  ID = "d1f9jvfuta01jm72drnfp3"
  Name = "App.Core.Connect.OnAliasLogin"
  Enabled = true
  Match = "#login$"
  Send = ""
  Script = "App.Core.Connect.OnAliasLogin"
  SendTo = 0
  Sequence = 100
  ExpandVariables = false
  Temporary = false
  OneShot = false
  Regexp = true
  Group = ""
  IgnoreCase = false
  KeepEvaluating = true
  Menu = false
  OmitFromLog = false
  Variable = ""
  ReverseSpeedwalk = false
  OmitFromOutput = false
  OmitFromCommandHistory = false

[[Aliases]]
  ID = "d1f9oq8ftm0dj9714eif9n"
  Name = "App.Core.Move.OnGoto"
  Enabled = true
  Match = "#to (.*)$"
  Send = ""
  Script = "App.Core.Move.OnGoto"
  SendTo = 0
  Sequence = 100
  ExpandVariables = false
  Temporary = false
  OneShot = false
  Regexp = true
  Group = ""
  IgnoreCase = false
  KeepEvaluating = false
  Menu = false
  OmitFromLog = false
  Variable = ""
  ReverseSpeedwalk = false
  OmitFromOutput = false
  OmitFromCommandHistory = false

[[Aliases]]
  ID = "d1fa70dmg66fmj6qr9en9"
  Name = "App.Core.Proposal.OnPrepare"
  Enabled = true
  Match = "^#prepare$"
  Send = ""
  Script = "App.Core.Proposal.OnPrepare"
  SendTo = 0
  Sequence = 100
  ExpandVariables = false
  Temporary = false
  OneShot = false
  Regexp = true
  Group = ""
  IgnoreCase = false
  KeepEvaluating = false
  Menu = false
  OmitFromLog = false
  Variable = ""
  ReverseSpeedwalk = false
  OmitFromOutput = false
  OmitFromCommandHistory = false

[[RequiredParams]]
  Name = "id"
  Desc = "用户ID"
  Intro = ""

[[RequiredParams]]
  Name = "password"
  Desc = "密码"
  Intro = "用户登陆密码"

[[RequiredParams]]
  Name = "quests"
  Desc = "任务列表设置"
  Intro = ""

[[RequiredParams]]
  Name = "quests2"
  Desc = "任务列表2设置"
  Intro = ""

[[RequiredParams]]
  Name = "quests3"
  Desc = "任务列表3设置"
  Intro = ""

[[RequiredParams]]
  Name = "study"
  Desc = "学习设置"
  Intro = ""

[[RequiredParams]]
  Name = "combat"
  Desc = "战斗设置"
  Intro = "战斗设置"

[[RequiredParams]]
  Name = "wield"
  Desc = "装备武器设置"
  Intro = "装备武器设置"

[[RequiredParams]]
  Name = "repair"
  Desc = "修理设置"
  Intro = ""

[[RequiredParams]]
  Name = "hp"
  Desc = "属性相关配置"
  Intro = "属性相关配置"

[[RequiredParams]]
  Name = "plan"
  Desc = "计划事件"
  Intro = "计划事件"

[[RequiredParams]]
  Name = "inv"
  Desc = "道具设置"
  Intro = ""

[[RequiredParams]]
  Name = "location"
  Desc = "位置设置"
  Intro = "location"

[[RequiredParams]]
  Name = "config"
  Desc = "其他配置"
  Intro = "其他配置"
