Type = "jscript"
Intro = "hell全能脚本"
Desc = ""
OnOpen = "onOpen"
OnClose = "onClose"
OnConnect = "onConnected"
OnDisconnect = "onDisconnected"
OnBroadcast = "onBroadcast"
OnFocus = ""
OnKeyUp = "OnKeyUp"
OnHUDClick = ""
OnResponse = "onResponse"
OnAssist = "onAssist"
OnBuffer = "onBuffer"
OnSubneg = ""
OnBufferMin = 0
OnBufferMax = 0
Channel = ""
Timers = []

[[Triggers]]
  ID = "d1f98164pfr1go7151pg53"
  Name = "App.Online"
  Enabled = true
  Match = "^"
  Send = ""
  ColourChangeType = 0
  Colour = 0
  Wildcard = 0
  SoundFileName = ""
  SoundIfInactive = false
  Script = "App.Online"
  SendTo = 0
  Sequence = 99
  ExpandVariables = false
  Temporary = false
  OneShot = false
  Regexp = true
  Repeat = false
  MultiLine = false
  LinesToMatch = 0
  WildcardLowerCase = false
  Group = ""
  IgnoreCase = false
  KeepEvaluating = true
  OmitFromLog = false
  OmitFromOutput = false
  Inverse = false
  Italic = false
  Variable = ""

[[Triggers]]
  ID = "d1f980vq1qbpo17151pfv6"
  Name = "App.Core.Room.OnExits"
  Enabled = true
  Match = "^    这里(唯一的出口是|明显的出口是|没有任何明显的出路)(.*)"
  Send = ""
  ColourChangeType = 0
  Colour = 0
  Wildcard = 0
  SoundFileName = ""
  SoundIfInactive = false
  Script = "App.Core.Room.OnExits"
  SendTo = 0
  Sequence = 100
  ExpandVariables = false
  Temporary = false
  OneShot = false
  Regexp = true
  Repeat = false
  MultiLine = false
  LinesToMatch = 0
  WildcardLowerCase = false
  Group = ""
  IgnoreCase = false
  KeepEvaluating = true
  OmitFromLog = false
  OmitFromOutput = false
  Inverse = false
  Italic = false
  Variable = ""

[[Triggers]]
  ID = "d1f985tqb73ivs7151pk8d"
  Name = "App.Core.Room.OnObj"
  Enabled = true
  Match = "^    ([^()]+)\\(([a-zA-Z ]+)\\)(\\s*<.+>)*(\\s*\\[.+\\])*$"
  Send = ""
  ColourChangeType = 0
  Colour = 0
  Wildcard = 0
  SoundFileName = ""
  SoundIfInactive = false
  Script = "App.Core.Room.OnObj"
  SendTo = 0
  Sequence = 100
  ExpandVariables = false
  Temporary = false
  OneShot = false
  Regexp = true
  Repeat = false
  MultiLine = false
  LinesToMatch = 0
  WildcardLowerCase = false
  Group = ""
  IgnoreCase = false
  KeepEvaluating = true
  OmitFromLog = false
  OmitFromOutput = false
  Inverse = false
  Italic = false
  Variable = ""

[[Aliases]]
  ID = "d1f9jvfuta01jm72drnfp3"
  Name = "App.Core.Connect.OnAliasLogin"
  Enabled = true
  Match = "#login$"
  Send = ""
  Script = "App.Core.Connect.OnAliasLogin"
  SendTo = 0
  Sequence = 100
  ExpandVariables = false
  Temporary = false
  OneShot = false
  Regexp = true
  Group = ""
  IgnoreCase = false
  KeepEvaluating = true
  Menu = false
  OmitFromLog = false
  Variable = ""
  ReverseSpeedwalk = false
  OmitFromOutput = false
  OmitFromCommandHistory = false

[[RequiredParams]]
  Name = "id"
  Desc = "用户ID"
  Intro = ""

[[RequiredParams]]
  Name = "password"
  Desc = "密码"
  Intro = "用户登陆密码"
