Type = "jscript"
Intro = "hell全能脚本"
Desc = ""
OnOpen = "onOpen"
OnClose = "onClose"
OnConnect = "onConnected"
OnDisconnect = "onDisconnected"
OnBroadcast = "onBroadcast"
OnFocus = ""
OnKeyUp = "OnKeyUp"
OnHUDClick = ""
OnResponse = "onResponse"
OnAssist = "onAssist"
OnBuffer = ""
OnSubneg = ""
OnBufferMin = 0
OnBufferMax = 0
Channel = ""
Triggers = []
Timers = []
Aliases = []
