(function(App){
App.Data.Busy={}
world.EnableTimer("App.Core.OnBusyRetry",false)
App.Core.OnBusyEnd=function(name, output, wildcards){
    world.EnableTimer("App.Core.OnBusyRetry",false)
    App.RaiseStateEvent('nobusy')
}
App.Core.OnBusyRetry=function(name){
    App.Send("bai")
}
App.Core.CheckBusy=function(callback,data){
    world.EnableTimer("App.Core.OnBusyRetry",true)
    world.ResetTimer("App.Core.OnBusyRetry")
    App.Data.Busy={
        Callback:callback,
        Data:data,
    }
    App.Send("bai")
}
})(App)