App.Load("core/action.js")
App.Load("core/init.js")
App.Load("core/state.js")
App.Load("core/automaton.js")
App.Load("core/cooldown.js")
App.Load("core/command.js")
App.Load("core/send.js")
App.Load("core/check.js")
App.Load("core/busy.js")
App.Load("core/item.js")
App.Load("core/repair.js")

App.Load("core/proposal.js")

App.Load("core/player.js")
App.Load("core/inv.js")
App.Load("core/room.js")
App.Load("core/response.js")
App.Load("core/connect.js")
App.Load("core/move.js")